// Mock data for development - bypasses Supabase when NEXT_PUBLIC_DEV_MODE=true

import type { Contact, Workspace, Conversation, Message, ConversationWithContact, Article, Webinar } from '@/types/database'

export const MOCK_WORKSPACE: Workspace = {
  id: 'dev-workspace-001',
  name: 'Eagle Overseas Education',
  slug: 'demo',
  owner_id: 'dev-user-001',
  kapso_phone_id: '647015955153740',
  settings: {
    kapso_api_key: process.env.KAPSO_API_KEY || '',
    whatsapp_number: '+62 xxx xxxx xxxx',
    whatsapp_name: 'Jonathan Wandiyanto',
  },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
}

export const MOCK_CONTACTS: Contact[] = [
  // Real contact from Kapso
  {
    id: 'contact-kapso-001',
    workspace_id: 'dev-workspace-001',
    phone: '+6285693542822',
    name: 'dap4_ratu_akhmar',
    email: null,
    lead_score: 50,
    lead_status: 'new',
    tags: ['Student', 'Immigration'],
    metadata: {
      source: 'Facebook CTWA',
      interest: 'Family Immigration',
      kapso_conversation_id: '366a22b7-11d6-4b9f-b721-9ec21a7054f8'
    },
    created_at: '2026-01-14T05:18:00Z',
    updated_at: '2026-01-14T08:15:00Z',
  },
  {
    id: 'contact-kapso-002',
    workspace_id: 'dev-workspace-001',
    phone: '+62unknown',
    name: 'A',
    email: null,
    lead_score: 30,
    lead_status: 'new',
    tags: [],
    metadata: { source: 'Referral Link' },
    created_at: '2026-01-14T08:00:00Z',
    updated_at: '2026-01-14T08:00:00Z',
  },
  {
    id: 'contact-001',
    workspace_id: 'dev-workspace-001',
    phone: '+62812345678',
    name: 'Ahmad Rizky',
    email: 'ahmad@example.com',
    lead_score: 85,
    lead_status: 'hot',
    tags: ['Premium', 'Jakarta'],
    metadata: { source: 'Website Form', interest: 'Personal Training' },
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
  },
  {
    id: 'contact-002',
    workspace_id: 'dev-workspace-001',
    phone: '+62887654321',
    name: 'Siti Nurhaliza',
    email: 'siti@example.com',
    lead_score: 65,
    lead_status: 'warm',
    tags: ['Bali'],
    metadata: { source: 'Referral' },
    created_at: '2024-01-09T14:30:00Z',
    updated_at: '2024-01-09T14:30:00Z',
  },
  {
    id: 'contact-003',
    workspace_id: 'dev-workspace-001',
    phone: '+62811223344',
    name: 'Budi Santoso',
    email: null,
    lead_score: 30,
    lead_status: 'cold',
    tags: [],
    metadata: {},
    created_at: '2024-01-08T09:15:00Z',
    updated_at: '2024-01-08T09:15:00Z',
  },
  {
    id: 'contact-004',
    workspace_id: 'dev-workspace-001',
    phone: '+62899887766',
    name: 'Dewi Lestari',
    email: 'dewi.lestari@company.com',
    lead_score: 95,
    lead_status: 'converted',
    tags: ['VIP', 'Corporate', 'Surabaya'],
    metadata: { source: 'LinkedIn', company: 'PT Maju Jaya' },
    created_at: '2024-01-05T11:20:00Z',
    updated_at: '2024-01-12T16:45:00Z',
  },
  {
    id: 'contact-005',
    workspace_id: 'dev-workspace-001',
    phone: '+62877665544',
    name: null,
    email: null,
    lead_score: 10,
    lead_status: 'new',
    tags: [],
    metadata: {},
    created_at: '2024-01-14T08:00:00Z',
    updated_at: '2024-01-14T08:00:00Z',
  },
  {
    id: 'contact-006',
    workspace_id: 'dev-workspace-001',
    phone: '+62833221100',
    name: 'Rudi Hermawan',
    email: 'rudi.h@gmail.com',
    lead_score: 45,
    lead_status: 'lost',
    tags: ['Bandung'],
    metadata: { reason: 'Price too high' },
    created_at: '2024-01-03T13:00:00Z',
    updated_at: '2024-01-11T10:00:00Z',
  },
]

export const isDevMode = () => process.env.NEXT_PUBLIC_DEV_MODE === 'true'

// Mock conversations linked to existing contacts
export const MOCK_CONVERSATIONS_RAW: Conversation[] = [
  // Real conversations from Kapso
  {
    id: 'conv-kapso-001',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-kapso-001', // dap4_ratu_akhmar - student
    status: 'open',
    assigned_to: null,
    unread_count: 4,
    last_message_at: '2026-01-14T08:15:00Z',
    last_message_preview: 'saya apa aja bisa insyaallah',
    created_at: '2026-01-14T05:18:00Z',
    updated_at: '2026-01-14T08:15:00Z',
  },
  {
    id: 'conv-kapso-002',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-kapso-002', // A - referral link
    status: 'open',
    assigned_to: null,
    unread_count: 1,
    last_message_at: '2026-01-14T08:00:00Z',
    last_message_preview: 'https://lynk.id/iutami',
    created_at: '2026-01-14T08:00:00Z',
    updated_at: '2026-01-14T08:00:00Z',
  },
  {
    id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-001', // Ahmad Rizky - hot lead
    status: 'open',
    assigned_to: null,
    unread_count: 2,
    last_message_at: '2024-01-14T09:30:00Z',
    last_message_preview: 'Great! When can we schedule the consultation?',
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-14T09:30:00Z',
  },
  {
    id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-002', // Siti Nurhaliza - warm lead
    status: 'open',
    assigned_to: null,
    unread_count: 0,
    last_message_at: '2024-01-13T16:45:00Z',
    last_message_preview: 'Thank you for the information!',
    created_at: '2024-01-09T14:30:00Z',
    updated_at: '2024-01-13T16:45:00Z',
  },
  {
    id: 'conv-003',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-004', // Dewi Lestari - converted
    status: 'open',
    assigned_to: null,
    unread_count: 1,
    last_message_at: '2024-01-14T08:15:00Z',
    last_message_preview: 'Hi, I have a question about my membership',
    created_at: '2024-01-05T11:20:00Z',
    updated_at: '2024-01-14T08:15:00Z',
  },
  {
    id: 'conv-004',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-005', // Unknown contact - new lead
    status: 'open',
    assigned_to: null,
    unread_count: 3,
    last_message_at: '2024-01-14T07:00:00Z',
    last_message_preview: 'Hello, I saw your ad and wanted to learn more',
    created_at: '2024-01-14T07:00:00Z',
    updated_at: '2024-01-14T07:00:00Z',
  },
  {
    id: 'conv-005',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-003', // Budi Santoso - cold lead
    status: 'closed',
    assigned_to: null,
    unread_count: 0,
    last_message_at: '2024-01-08T11:00:00Z',
    last_message_preview: 'I will think about it and get back to you',
    created_at: '2024-01-08T09:15:00Z',
    updated_at: '2024-01-08T11:00:00Z',
  },
]

// Join conversations with contacts for complete data
export const MOCK_CONVERSATIONS: ConversationWithContact[] = MOCK_CONVERSATIONS_RAW.map((conv) => ({
  ...conv,
  contact: MOCK_CONTACTS.find((c) => c.id === conv.contact_id)!,
}))

// Mock messages across conversations
export const MOCK_MESSAGES: Message[] = [
  // Real Conversation - dap4_ratu_akhmar (student from Kapso)
  {
    id: 'msg-kapso-001',
    conversation_id: 'conv-kapso-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-kapso-001',
    content: 'https://lynk.id/iutami?fbclid=IwY2xjawPTzftleHRuA2FlbQlx...',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-real-001',
    metadata: { source: 'Facebook CTWA' },
    created_at: '2026-01-14T05:18:00Z',
  },
  {
    id: 'msg-kapso-002',
    conversation_id: 'conv-kapso-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-kapso-001',
    content: 'mohon maaf kalau untuk imigrasi sekeluarga tapi disana bekerja. bisa atau tidak ya',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-real-002',
    metadata: {},
    created_at: '2026-01-14T08:13:00Z',
  },
  {
    id: 'msg-kapso-003',
    conversation_id: 'conv-kapso-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-kapso-001',
    content: 'suami saya sebagai supir',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-real-003',
    metadata: {},
    created_at: '2026-01-14T08:14:00Z',
  },
  {
    id: 'msg-kapso-004',
    conversation_id: 'conv-kapso-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-kapso-001',
    content: 'saya apa aja bisa insyaallah',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-real-004',
    metadata: {},
    created_at: '2026-01-14T08:15:00Z',
  },
  // Real Conversation - A (referral link)
  {
    id: 'msg-kapso-005',
    conversation_id: 'conv-kapso-002',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-kapso-002',
    content: 'https://lynk.id/iutami',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-real-005',
    metadata: {},
    created_at: '2026-01-14T08:00:00Z',
  },
  // Conversation 1 - Ahmad Rizky (hot lead)
  {
    id: 'msg-001',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-001',
    content: 'Hi, I am interested in your personal training program',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-001',
    metadata: {},
    created_at: '2024-01-10T10:05:00Z',
  },
  {
    id: 'msg-002',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'user',
    sender_id: 'dev-user-001',
    content: 'Hi Ahmad! Thanks for reaching out. We have several personal training packages available. What are your fitness goals?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-002',
    metadata: {},
    created_at: '2024-01-10T10:15:00Z',
  },
  {
    id: 'msg-003',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-001',
    content: 'I want to lose weight and build muscle. I am available in the evenings',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-003',
    metadata: {},
    created_at: '2024-01-12T18:30:00Z',
  },
  {
    id: 'msg-004',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'user',
    sender_id: 'dev-user-001',
    content: 'Perfect! We have evening slots available. Let me share our packages with you.',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-004',
    metadata: {},
    created_at: '2024-01-12T18:45:00Z',
  },
  {
    id: 'msg-005',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'user',
    sender_id: 'dev-user-001',
    content: null,
    message_type: 'image',
    media_url: 'https://example.com/packages.jpg',
    kapso_message_id: 'kapso-005',
    metadata: { caption: 'Our training packages' },
    created_at: '2024-01-12T18:46:00Z',
  },
  {
    id: 'msg-006',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-001',
    content: 'Great! When can we schedule the consultation?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-006',
    metadata: {},
    created_at: '2024-01-14T09:30:00Z',
  },

  // Conversation 2 - Siti Nurhaliza (warm lead)
  {
    id: 'msg-007',
    conversation_id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-002',
    content: 'Hello, do you offer group fitness classes?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-007',
    metadata: {},
    created_at: '2024-01-09T14:35:00Z',
  },
  {
    id: 'msg-008',
    conversation_id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'user',
    sender_id: 'dev-user-001',
    content: 'Hi Siti! Yes, we have yoga, pilates, and HIIT classes. Which one interests you?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-008',
    metadata: {},
    created_at: '2024-01-09T15:00:00Z',
  },
  {
    id: 'msg-009',
    conversation_id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-002',
    content: 'I am interested in yoga. What is the schedule?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-009',
    metadata: {},
    created_at: '2024-01-13T16:30:00Z',
  },
  {
    id: 'msg-010',
    conversation_id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'user',
    sender_id: 'dev-user-001',
    content: 'Our yoga classes are Mon, Wed, Fri at 7am and 6pm. Would you like to try a free session?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-010',
    metadata: {},
    created_at: '2024-01-13T16:40:00Z',
  },
  {
    id: 'msg-011',
    conversation_id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-002',
    content: 'Thank you for the information!',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-011',
    metadata: {},
    created_at: '2024-01-13T16:45:00Z',
  },

  // Conversation 3 - Dewi Lestari (converted)
  {
    id: 'msg-012',
    conversation_id: 'conv-003',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'user',
    sender_id: 'dev-user-001',
    content: 'Welcome to the family, Dewi! Your VIP membership is now active.',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-012',
    metadata: {},
    created_at: '2024-01-12T16:50:00Z',
  },
  {
    id: 'msg-013',
    conversation_id: 'conv-003',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-004',
    content: 'Thank you! Very excited to start.',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-013',
    metadata: {},
    created_at: '2024-01-12T17:00:00Z',
  },
  {
    id: 'msg-014',
    conversation_id: 'conv-003',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-004',
    content: 'Hi, I have a question about my membership',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-014',
    metadata: {},
    created_at: '2024-01-14T08:15:00Z',
  },

  // Conversation 4 - Unknown contact (new)
  {
    id: 'msg-015',
    conversation_id: 'conv-004',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-005',
    content: 'Hello, I saw your ad and wanted to learn more',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-015',
    metadata: {},
    created_at: '2024-01-14T07:00:00Z',
  },
  {
    id: 'msg-016',
    conversation_id: 'conv-004',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-005',
    content: 'What services do you offer?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-016',
    metadata: {},
    created_at: '2024-01-14T07:01:00Z',
  },
  {
    id: 'msg-017',
    conversation_id: 'conv-004',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-005',
    content: 'And what are your prices?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-017',
    metadata: {},
    created_at: '2024-01-14T07:02:00Z',
  },

  // Conversation 5 - Budi Santoso (cold)
  {
    id: 'msg-018',
    conversation_id: 'conv-005',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-003',
    content: 'How much is a monthly membership?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-018',
    metadata: {},
    created_at: '2024-01-08T09:20:00Z',
  },
  {
    id: 'msg-019',
    conversation_id: 'conv-005',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'user',
    sender_id: 'dev-user-001',
    content: 'Hi Budi! Our monthly membership starts at Rp 500,000. We also have quarterly and annual plans with discounts.',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-019',
    metadata: {},
    created_at: '2024-01-08T10:30:00Z',
  },
  {
    id: 'msg-020',
    conversation_id: 'conv-005',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-003',
    content: 'I will think about it and get back to you',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'kapso-020',
    metadata: {},
    created_at: '2024-01-08T11:00:00Z',
  },
]

// Website Manager mock data
export const mockArticles: Article[] = [
  {
    id: 'article-1',
    workspace_id: 'dev-workspace-001',
    title: 'How to Choose the Right University',
    slug: 'how-to-choose-university',
    excerpt: 'A comprehensive guide to selecting the perfect university for your education abroad journey.',
    content: '# How to Choose the Right University\n\nChoosing where to study is one of the most important decisions...',
    cover_image_url: null,
    status: 'published',
    published_at: '2026-01-10T10:00:00Z',
    created_at: '2026-01-08T10:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'article-2',
    workspace_id: 'dev-workspace-001',
    title: 'Visa Application Tips for Indonesian Students',
    slug: 'visa-tips-indonesian',
    excerpt: 'Essential tips to make your student visa application process smooth and successful.',
    content: null,
    cover_image_url: null,
    status: 'draft',
    published_at: null,
    created_at: '2026-01-12T10:00:00Z',
    updated_at: '2026-01-12T10:00:00Z',
  },
]

export const mockWebinars: Webinar[] = [
  {
    id: 'webinar-1',
    workspace_id: 'dev-workspace-001',
    title: 'Study in Australia Info Session',
    slug: 'study-australia-info',
    description: 'Learn about studying in Australia, visa requirements, and scholarship opportunities.',
    cover_image_url: null,
    scheduled_at: '2026-01-25T14:00:00Z',
    duration_minutes: 60,
    meeting_url: 'https://zoom.us/j/example',
    max_registrations: 100,
    status: 'published',
    published_at: '2026-01-14T10:00:00Z',
    created_at: '2026-01-13T10:00:00Z',
    updated_at: '2026-01-14T10:00:00Z',
  },
  {
    id: 'webinar-2',
    workspace_id: 'dev-workspace-001',
    title: 'UK University Application Workshop',
    slug: 'uk-application-workshop',
    description: 'Hands-on workshop for applying to UK universities through UCAS.',
    cover_image_url: null,
    scheduled_at: '2026-02-01T15:00:00Z',
    duration_minutes: 90,
    meeting_url: null,
    max_registrations: 50,
    status: 'draft',
    published_at: null,
    created_at: '2026-01-14T10:00:00Z',
    updated_at: '2026-01-14T10:00:00Z',
  },
]
