// Mock data for development - bypasses Convex when NEXT_PUBLIC_DEV_MODE=true
// This allows fully OFFLINE local development at localhost:3000/demo

import type { Contact, Workspace, Conversation, Message, ConversationWithContact, Article, Webinar, WorkspaceMember, Profile } from '@/types/database'

export type MockTeamMember = WorkspaceMember & { profile: Profile | null }

// =============================================================================
// CONVEX-COMPATIBLE MOCK WORKSPACE
// Used by server components to avoid Convex calls when offline
// =============================================================================
export type MockConvexWorkspace = {
  _id: string  // Fake Convex ID format
  _creationTime: number
  name: string
  slug: string
  owner_id: string
  kapso_phone_id: string | null
  meta_access_token?: string
  settings: {
    kapso_api_key?: string
    whatsapp_number?: string
    whatsapp_name?: string
    contact_tags?: string[]
    main_form_fields?: string[]
    form_field_scores?: Record<string, number>
    lead_statuses?: {
      key: string
      label: string
      color: string
      enabled: boolean
    }[]
  } | null
  created_at: number
  updated_at: number
}

export const MOCK_CONVEX_WORKSPACE: MockConvexWorkspace = {
  _id: 'demo',  // Must match API route dev mode check: isDevMode() && workspaceId === 'demo'
  _creationTime: Date.now(),
  name: 'Eagle Overseas Education',
  slug: 'demo',
  owner_id: 'dev-user-001',
  kapso_phone_id: '647015955153740',
  settings: {
    kapso_api_key: 'mock-api-key',
    whatsapp_number: '+62 xxx xxxx xxxx',
    whatsapp_name: 'Jonathan Wandiyanto',
    contact_tags: ['Hot Lead', 'Student', 'Parent', 'Follow Up'],
    main_form_fields: ['Pendidikan', 'Jurusan', 'Aktivitas', 'Negara Tujuan', 'Budget', 'Target Berangkat', 'Level Bahasa Inggris', 'Goals'],
    form_field_scores: {
      // Education Level (dropdown)
      'Pendidikan:SMA': 2,
      'Pendidikan:D3': 4,
      'Pendidikan:S1': 6,
      'Pendidikan:S2': 8,
      'Pendidikan:S3': 10,
      // Major (open-ended)
      'Jurusan': 5,
      // Current Activity (dropdown)
      'Aktivitas:kuliah': 5,
      'Aktivitas:gap_year': 8,
      'Aktivitas:working': 15,
      'Aktivitas:fresh_graduate': 12,
      'Aktivitas:others': 10,
      // Target Country (open-ended)
      'Negara Tujuan': 5,
      // Budget (dropdown)
      'Budget:<100jt': 4,
      'Budget:100-300jt': 8,
      'Budget:300-500jt': 12,
      'Budget:500jt-1m': 16,
      'Budget:>1m': 20,
      'Budget:beasiswa': 4,
      // Target Departure (dropdown)
      'Target Berangkat:<3bulan': 15,
      'Target Berangkat:3-6bulan': 12,
      'Target Berangkat:6-12bulan': 9,
      'Target Berangkat:1-2tahun': 6,
      'Target Berangkat:fleksibel': 3,
      // English Level (dropdown)
      'Level Bahasa Inggris:pemula': 5,
      'Level Bahasa Inggris:menengah': 10,
      'Level Bahasa Inggris:mahir': 15,
      'Level Bahasa Inggris:native': 25,
      'Level Bahasa Inggris:skor': 25,
      // Goals (open-ended)
      'Goals': 5,
    },
    lead_statuses: [
      { key: 'new', label: 'New', color: '#808080', enabled: true },
      { key: 'cold', label: 'Cold', color: '#3b82f6', enabled: true },
      { key: 'warm', label: 'Warm', color: '#f59e0b', enabled: true },
      { key: 'hot', label: 'Hot', color: '#ef4444', enabled: true },
      { key: 'client', label: 'Client', color: '#10b981', enabled: true },
      { key: 'lost', label: 'Lost', color: '#6b7280', enabled: false },
    ],
  },
  created_at: Date.now(),
  updated_at: Date.now(),
}

// Helper to check if we should use mock data (dev mode + demo slug)
export const shouldUseMockData = (slug: string) => {
  return isDevMode() && slug === 'demo'
}

// Mock team members for dev mode
export const MOCK_TEAM_MEMBERS: MockTeamMember[] = [
  {
    id: 'member-001',
    workspace_id: 'dev-workspace-001',
    user_id: 'dev-user-001',
    role: 'owner',
    must_change_password: false,
    settings: null,
    created_at: '2024-01-01T00:00:00Z',
    profile: {
      id: 'dev-user-001',
      email: 'jonathan@eagle.edu',
      full_name: 'Jonathan Wandiyanto',
      avatar_url: null,
      is_admin: false,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  },
  {
    id: 'member-002',
    workspace_id: 'dev-workspace-001',
    user_id: 'dev-user-002',
    role: 'admin',
    must_change_password: false,
    settings: null,
    created_at: '2024-01-01T00:00:00Z',
    profile: {
      id: 'dev-user-002',
      email: 'sarah@eagle.edu',
      full_name: 'Sarah Chen',
      avatar_url: null,
      is_admin: false,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  },
  {
    id: 'member-003',
    workspace_id: 'dev-workspace-001',
    user_id: 'dev-user-003',
    role: 'member',
    must_change_password: false,
    settings: null,
    created_at: '2024-01-01T00:00:00Z',
    profile: {
      id: 'dev-user-003',
      email: 'budi@eagle.edu',
      full_name: 'Budi Santoso',
      avatar_url: null,
      is_admin: false,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  },
]

export const MOCK_WORKSPACE: Workspace = {
  id: 'dev-workspace-001',
  name: 'Eagle Overseas Education',
  slug: 'demo',
  owner_id: 'dev-user-001',
  kapso_phone_id: '647015955153740',
  settings: {
    kapso_api_key: process.env.KAPSO_API_KEY || '',
    whatsapp_number: '+62 xxx xxxx xxxx',
    whatsapp_name: 'Jonathan Wandiyanto',
  },
  description: null,
  meta_access_token: null,
  meta_business_account_id: null,
  status: 'active',
  suspended_at: null,
  suspended_by: null,
  suspension_reason: null,
  wa_phone_number: null,
  workspace_type: 'client',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
}

// Mock contacts - synced with /api/contacts for consistency
export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'contact-001',
    workspace_id: 'dev-workspace-001',
    phone: '+6281234567890',
    phone_normalized: '+6281234567890',
    name: 'Budi Santoso',
    kapso_name: 'Budi Santoso',
    email: 'budi@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Student', 'Hot Lead'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'IT / Computer Science',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Australia',
        'Budget': '300-500jt',
        'Target Berangkat': '3-6bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Master degree in Computer Science',
      },
    },
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-20T14:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-002',
    workspace_id: 'dev-workspace-001',
    phone: '+6282345678901',
    phone_normalized: '+6282345678901',
    name: 'Siti Rahayu',
    kapso_name: 'Siti Rahayu',
    email: 'siti.rahayu@yahoo.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Parent', 'Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Bisnis / Manajemen',
        'Aktivitas': 'kuliah',
        'Negara Tujuan': 'Malaysia',
        'Budget': '100-300jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Bachelor degree in Business Management',
      },
    },
    created_at: '2026-01-18T09:00:00Z',
    updated_at: '2026-01-22T11:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-003',
    workspace_id: 'dev-workspace-001',
    phone: '+6283456789012',
    phone_normalized: '+6283456789012',
    name: 'Ahmad Rizky',
    kapso_name: 'Ahmad Rizky',
    email: 'ahmad.rizky@outlook.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Engineering',
        'Aktivitas': 'fresh_graduate',
        'Negara Tujuan': 'UK',
        'Budget': '500jt-1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'PhD in Mechanical Engineering',
        'Catatan': 'IELTS 7.5, ready to start ASAP',
      },
    },
    created_at: '2026-01-20T08:00:00Z',
    updated_at: '2026-01-23T16:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-004',
    workspace_id: 'dev-workspace-001',
    phone: '+6284567890123',
    phone_normalized: '+6284567890123',
    name: 'Dewi Lestari',
    kapso_name: 'Dewi Lestari',
    email: null,
    lead_score: 0,
    lead_status: 'cold',
    tags: ['Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Design',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Study graphic design',
      },
    },
    created_at: '2026-01-21T14:00:00Z',
    updated_at: '2026-01-21T14:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-005',
    workspace_id: 'dev-workspace-001',
    phone: '+6285678901234',
    phone_normalized: '+6285678901234',
    name: 'Rina Wijaya',
    kapso_name: 'Rina Wijaya',
    email: 'rina.w@gmail.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Medicine',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Canada',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'Specialist training in Cardiology',
      },
    },
    created_at: '2026-01-22T10:00:00Z',
    updated_at: '2026-01-24T09:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-006',
    workspace_id: 'dev-workspace-001',
    phone: '+6286789012345',
    phone_normalized: '+6286789012345',
    name: 'Arif Budiman',
    kapso_name: 'Arif Budiman',
    email: 'arif.b@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-002',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S2',
        'Jurusan': 'Data Science',
        'Aktivitas': 'working',
        'Negara Tujuan': 'USA',
        'Budget': '>1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'PhD in AI and Machine Learning',
      },
    },
    created_at: '2026-01-10T08:30:00Z',
    updated_at: '2026-01-25T10:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-007',
    workspace_id: 'dev-workspace-001',
    phone: '+6287890123456',
    phone_normalized: '+6287890123456',
    name: 'Maya Putri',
    kapso_name: 'Maya Putri',
    email: null,
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student', 'Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Psychology',
        'Aktivitas': 'gap_year',
        'Negara Tujuan': 'Singapore',
        'Budget': '100-300jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Bachelor in Clinical Psychology',
      },
    },
    created_at: '2026-01-19T11:15:00Z',
    updated_at: '2026-01-23T14:20:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-008',
    workspace_id: 'dev-workspace-001',
    phone: '+6288901234567',
    phone_normalized: '+6288901234567',
    name: 'Rudi Hartono',
    kapso_name: 'Rudi Hartono',
    email: 'rudi.hartono@yahoo.com',
    lead_score: 0,
    lead_status: 'cold',
    tags: ['Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'D3',
        'Jurusan': 'Hospitality',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': '1-2tahun',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Hotel management certification',
      },
    },
    created_at: '2026-01-17T13:00:00Z',
    updated_at: '2026-01-17T13:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-009',
    workspace_id: 'dev-workspace-001',
    phone: '+6289012345678',
    phone_normalized: '+6289012345678',
    name: 'Linda Sari',
    kapso_name: 'Linda Sari',
    email: 'linda.sari@outlook.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Parent'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Architecture',
        'Aktivitas': 'kuliah',
        'Negara Tujuan': 'Netherlands',
        'Budget': '500jt-1m',
        'Target Berangkat': '3-6bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'Master in Urban Planning',
      },
    },
    created_at: '2026-01-12T09:45:00Z',
    updated_at: '2026-01-26T16:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-010',
    workspace_id: 'dev-workspace-001',
    phone: '+6281012345679',
    phone_normalized: '+6281012345679',
    name: 'Hendra Gunawan',
    kapso_name: 'Hendra Gunawan',
    email: 'hendra.g@gmail.com',
    lead_score: 0,
    lead_status: 'new',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Accounting',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Australia',
        'Budget': '300-500jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'CPA certification and Master',
      },
    },
    created_at: '2026-01-24T10:20:00Z',
    updated_at: '2026-01-24T10:20:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-011',
    workspace_id: 'dev-workspace-001',
    phone: '+6282123456780',
    phone_normalized: '+6282123456780',
    name: 'Putri Indah',
    kapso_name: 'Putri Indah',
    email: 'putri.indah@yahoo.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student', 'Follow Up'],
    assigned_to: 'dev-user-002',
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Law',
        'Aktivitas': 'fresh_graduate',
        'Negara Tujuan': 'UK',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'LLM in International Law',
      },
    },
    created_at: '2026-01-16T14:00:00Z',
    updated_at: '2026-01-22T09:15:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-012',
    workspace_id: 'dev-workspace-001',
    phone: '+6283234567891',
    phone_normalized: '+6283234567891',
    name: 'Agus Salim',
    kapso_name: 'Agus Salim',
    email: null,
    lead_score: 0,
    lead_status: 'cold',
    tags: ['Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Film Production',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Learn filmmaking',
      },
    },
    created_at: '2026-01-20T15:30:00Z',
    updated_at: '2026-01-20T15:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-013',
    workspace_id: 'dev-workspace-001',
    phone: '+6284345678902',
    phone_normalized: '+6284345678902',
    name: 'Sinta Dewi',
    kapso_name: 'Sinta Dewi',
    email: 'sinta.dewi@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Finance',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Singapore',
        'Budget': '>1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'native',
        'Goals': 'MBA at NUS',
      },
    },
    created_at: '2026-01-11T08:00:00Z',
    updated_at: '2026-01-27T11:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-014',
    workspace_id: 'dev-workspace-001',
    phone: '+6285456789013',
    phone_normalized: '+6285456789013',
    name: 'Wahyu Nugroho',
    kapso_name: 'Wahyu Nugroho',
    email: 'wahyu.n@outlook.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'D3',
        'Jurusan': 'Nursing',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Australia',
        'Budget': '100-300jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Bachelor of Nursing completion',
      },
    },
    created_at: '2026-01-18T12:00:00Z',
    updated_at: '2026-01-24T10:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-015',
    workspace_id: 'dev-workspace-001',
    phone: '+6286567890124',
    phone_normalized: '+6286567890124',
    name: 'Ratna Sari',
    kapso_name: 'Ratna Sari',
    email: 'ratna.sari@yahoo.com',
    lead_score: 0,
    lead_status: 'new',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Marketing',
        'Aktivitas': 'gap_year',
        'Negara Tujuan': 'Malaysia',
        'Budget': '100-300jt',
        'Target Berangkat': '1-2tahun',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Bachelor in Digital Marketing',
      },
    },
    created_at: '2026-01-25T09:00:00Z',
    updated_at: '2026-01-25T09:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-016',
    workspace_id: 'dev-workspace-001',
    phone: '+6287678901235',
    phone_normalized: '+6287678901235',
    name: 'Bambang Suryadi',
    kapso_name: 'Bambang Suryadi',
    email: 'bambang.s@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Parent'],
    assigned_to: 'dev-user-002',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Civil Engineering',
        'Aktivitas': 'kuliah',
        'Negara Tujuan': 'Canada',
        'Budget': '500jt-1m',
        'Target Berangkat': '3-6bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'Engineering degree with co-op',
      },
    },
    created_at: '2026-01-13T10:30:00Z',
    updated_at: '2026-01-26T14:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-017',
    workspace_id: 'dev-workspace-001',
    phone: '+6288789012346',
    phone_normalized: '+6288789012346',
    name: 'Fitri Rahmawati',
    kapso_name: 'Fitri Rahmawati',
    email: null,
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student', 'Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Pharmacy',
        'Aktivitas': 'fresh_graduate',
        'Negara Tujuan': 'UK',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Master in Clinical Pharmacy',
      },
    },
    created_at: '2026-01-19T08:45:00Z',
    updated_at: '2026-01-23T16:20:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-018',
    workspace_id: 'dev-workspace-001',
    phone: '+6289890123457',
    phone_normalized: '+6289890123457',
    name: 'Doni Prasetyo',
    kapso_name: 'Doni Prasetyo',
    email: 'doni.p@outlook.com',
    lead_score: 0,
    lead_status: 'cold',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Music Production',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Audio engineering certificate',
      },
    },
    created_at: '2026-01-21T16:00:00Z',
    updated_at: '2026-01-21T16:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-019',
    workspace_id: 'dev-workspace-001',
    phone: '+6281901234568',
    phone_normalized: '+6281901234568',
    name: 'Mega Pratiwi',
    kapso_name: 'Mega Pratiwi',
    email: 'mega.pratiwi@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Software Engineering',
        'Aktivitas': 'working',
        'Negara Tujuan': 'USA',
        'Budget': '>1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'Master in Computer Science at Stanford',
      },
    },
    created_at: '2026-01-09T07:30:00Z',
    updated_at: '2026-01-27T15:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-020',
    workspace_id: 'dev-workspace-001',
    phone: '+6282012345679',
    phone_normalized: '+6282012345679',
    name: 'Yudi Kurniawan',
    kapso_name: 'Yudi Kurniawan',
    email: 'yudi.k@yahoo.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'D3',
        'Jurusan': 'Graphic Design',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Australia',
        'Budget': '100-300jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Bachelor in Visual Communication',
      },
    },
    created_at: '2026-01-17T11:00:00Z',
    updated_at: '2026-01-23T13:45:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-021',
    workspace_id: 'dev-workspace-001',
    phone: '+6283123456790',
    phone_normalized: '+6283123456790',
    name: 'Novi Andriani',
    kapso_name: 'Novi Andriani',
    email: 'novi.andriani@gmail.com',
    lead_score: 0,
    lead_status: 'new',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Tourism',
        'Aktivitas': 'gap_year',
        'Negara Tujuan': 'Malaysia',
        'Budget': '100-300jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Diploma in Hospitality Management',
      },
    },
    created_at: '2026-01-26T10:15:00Z',
    updated_at: '2026-01-26T10:15:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-022',
    workspace_id: 'dev-workspace-001',
    phone: '+6284234567801',
    phone_normalized: '+6284234567801',
    name: 'Irwan Setiawan',
    kapso_name: 'Irwan Setiawan',
    email: 'irwan.setiawan@outlook.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-002',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S2',
        'Jurusan': 'Electrical Engineering',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Germany',
        'Budget': '500jt-1m',
        'Target Berangkat': '3-6bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'PhD in Renewable Energy',
      },
    },
    created_at: '2026-01-14T09:00:00Z',
    updated_at: '2026-01-27T10:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-023',
    workspace_id: 'dev-workspace-001',
    phone: '+6285345678912',
    phone_normalized: '+6285345678912',
    name: 'Ayu Lestari',
    kapso_name: 'Ayu Lestari',
    email: null,
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student', 'Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Public Health',
        'Aktivitas': 'fresh_graduate',
        'Negara Tujuan': 'Australia',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Master in Epidemiology',
      },
    },
    created_at: '2026-01-16T13:30:00Z',
    updated_at: '2026-01-22T15:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-024',
    workspace_id: 'dev-workspace-001',
    phone: '+6286456789023',
    phone_normalized: '+6286456789023',
    name: 'Taufik Hidayat',
    kapso_name: 'Taufik Hidayat',
    email: 'taufik.h@gmail.com',
    lead_score: 0,
    lead_status: 'cold',
    tags: ['Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Photography',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': '1-2tahun',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Photography diploma',
      },
    },
    created_at: '2026-01-23T14:00:00Z',
    updated_at: '2026-01-23T14:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-025',
    workspace_id: 'dev-workspace-001',
    phone: '+6287567890134',
    phone_normalized: '+6287567890134',
    name: 'Eka Nur',
    kapso_name: 'Eka Nur',
    email: 'eka.nur@yahoo.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Parent'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Economics',
        'Aktivitas': 'kuliah',
        'Negara Tujuan': 'UK',
        'Budget': '>1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'BSc Economics at LSE',
      },
    },
    created_at: '2026-01-10T08:00:00Z',
    updated_at: '2026-01-27T16:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-026',
    workspace_id: 'dev-workspace-001',
    phone: '+6288678901245',
    phone_normalized: '+6288678901245',
    name: 'Hadi Santoso',
    kapso_name: 'Hadi Santoso',
    email: 'hadi.santoso@gmail.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Mechanical Engineering',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Canada',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'Master in Automotive Engineering',
      },
    },
    created_at: '2026-01-15T12:00:00Z',
    updated_at: '2026-01-24T11:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-027',
    workspace_id: 'dev-workspace-001',
    phone: '+6289789012356',
    phone_normalized: '+6289789012356',
    name: 'Nurul Fadilah',
    kapso_name: 'Nurul Fadilah',
    email: 'nurul.f@outlook.com',
    lead_score: 0,
    lead_status: 'new',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Fashion Design',
        'Aktivitas': 'gap_year',
        'Negara Tujuan': 'Singapore',
        'Budget': '100-300jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Diploma in Fashion Design',
      },
    },
    created_at: '2026-01-27T09:00:00Z',
    updated_at: '2026-01-27T09:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-028',
    workspace_id: 'dev-workspace-001',
    phone: '+6281890123467',
    phone_normalized: '+6281890123467',
    name: 'Rizal Ramadan',
    kapso_name: 'Rizal Ramadan',
    email: 'rizal.r@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-002',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Biotechnology',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Netherlands',
        'Budget': '500jt-1m',
        'Target Berangkat': '3-6bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'PhD in Genetic Engineering',
      },
    },
    created_at: '2026-01-12T10:00:00Z',
    updated_at: '2026-01-26T13:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-029',
    workspace_id: 'dev-workspace-001',
    phone: '+6282901234578',
    phone_normalized: '+6282901234578',
    name: 'Dina Permata',
    kapso_name: 'Dina Permata',
    email: null,
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student', 'Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Social Work',
        'Aktivitas': 'fresh_graduate',
        'Negara Tujuan': 'Australia',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Master in Community Development',
      },
    },
    created_at: '2026-01-18T10:30:00Z',
    updated_at: '2026-01-23T12:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-030',
    workspace_id: 'dev-workspace-001',
    phone: '+6283012345689',
    phone_normalized: '+6283012345689',
    name: 'Fajar Pratama',
    kapso_name: 'Fajar Pratama',
    email: 'fajar.p@yahoo.com',
    lead_score: 0,
    lead_status: 'cold',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'D3',
        'Jurusan': 'Animation',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': '1-2tahun',
        'Level Bahasa Inggris': 'pemula',
        'Goals': '3D animation certificate',
      },
    },
    created_at: '2026-01-22T15:00:00Z',
    updated_at: '2026-01-22T15:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-031',
    workspace_id: 'dev-workspace-001',
    phone: '+6284123456790',
    phone_normalized: '+6284123456790',
    name: 'Laila Sari',
    kapso_name: 'Laila Sari',
    email: 'laila.sari@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'International Relations',
        'Aktivitas': 'working',
        'Negara Tujuan': 'UK',
        'Budget': '>1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'native',
        'Goals': 'Master at Oxford',
      },
    },
    created_at: '2026-01-11T07:00:00Z',
    updated_at: '2026-01-27T14:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-032',
    workspace_id: 'dev-workspace-001',
    phone: '+6285234567801',
    phone_normalized: '+6285234567801',
    name: 'Wawan Setiawan',
    kapso_name: 'Wawan Setiawan',
    email: 'wawan.s@outlook.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'D3',
        'Jurusan': 'Information Technology',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Malaysia',
        'Budget': '100-300jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Bachelor in Cybersecurity',
      },
    },
    created_at: '2026-01-17T08:30:00Z',
    updated_at: '2026-01-24T09:45:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-033',
    workspace_id: 'dev-workspace-001',
    phone: '+6286345678912',
    phone_normalized: '+6286345678912',
    name: 'Sri Mulyani',
    kapso_name: 'Sri Mulyani',
    email: null,
    lead_score: 0,
    lead_status: 'new',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Culinary Arts',
        'Aktivitas': 'gap_year',
        'Negara Tujuan': 'Australia',
        'Budget': '100-300jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Professional Chef training',
      },
    },
    created_at: '2026-01-26T11:00:00Z',
    updated_at: '2026-01-26T11:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-034',
    workspace_id: 'dev-workspace-001',
    phone: '+6287456789023',
    phone_normalized: '+6287456789023',
    name: 'Andi Wijaya',
    kapso_name: 'Andi Wijaya',
    email: 'andi.wijaya@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Parent'],
    assigned_to: 'dev-user-002',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Chemical Engineering',
        'Aktivitas': 'working',
        'Negara Tujuan': 'USA',
        'Budget': '500jt-1m',
        'Target Berangkat': '3-6bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'PhD in Materials Science',
      },
    },
    created_at: '2026-01-13T09:30:00Z',
    updated_at: '2026-01-27T11:45:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-035',
    workspace_id: 'dev-workspace-001',
    phone: '+6288567890134',
    phone_normalized: '+6288567890134',
    name: 'Vina Marlina',
    kapso_name: 'Vina Marlina',
    email: 'vina.marlina@yahoo.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student', 'Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Dentistry',
        'Aktivitas': 'fresh_graduate',
        'Negara Tujuan': 'Australia',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'Specialist in Orthodontics',
      },
    },
    created_at: '2026-01-16T14:30:00Z',
    updated_at: '2026-01-22T10:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-036',
    workspace_id: 'dev-workspace-001',
    phone: '+6289678901245',
    phone_normalized: '+6289678901245',
    name: 'Joko Widodo',
    kapso_name: 'Joko Widodo',
    email: 'joko.w@gmail.com',
    lead_score: 0,
    lead_status: 'cold',
    tags: ['Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Game Design',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': '1-2tahun',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Game development course',
      },
    },
    created_at: '2026-01-24T16:00:00Z',
    updated_at: '2026-01-24T16:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-037',
    workspace_id: 'dev-workspace-001',
    phone: '+6281789012356',
    phone_normalized: '+6281789012356',
    name: 'Sari Indah',
    kapso_name: 'Sari Indah',
    email: 'sari.indah@outlook.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S2',
        'Jurusan': 'Environmental Science',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Canada',
        'Budget': '>1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'PhD in Climate Change Research',
      },
    },
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-27T13:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-038',
    workspace_id: 'dev-workspace-001',
    phone: '+6282890123467',
    phone_normalized: '+6282890123467',
    name: 'Benny Kurniawan',
    kapso_name: 'Benny Kurniawan',
    email: null,
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'D3',
        'Jurusan': 'Web Development',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Singapore',
        'Budget': '100-300jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Bachelor in Software Engineering',
      },
    },
    created_at: '2026-01-18T09:45:00Z',
    updated_at: '2026-01-24T14:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-039',
    workspace_id: 'dev-workspace-001',
    phone: '+6283901234578',
    phone_normalized: '+6283901234578',
    name: 'Citra Dewi',
    kapso_name: 'Citra Dewi',
    email: 'citra.dewi@yahoo.com',
    lead_score: 0,
    lead_status: 'new',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Interior Design',
        'Aktivitas': 'gap_year',
        'Negara Tujuan': 'Malaysia',
        'Budget': '100-300jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Diploma in Interior Architecture',
      },
    },
    created_at: '2026-01-27T10:30:00Z',
    updated_at: '2026-01-27T10:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-040',
    workspace_id: 'dev-workspace-001',
    phone: '+6284012345689',
    phone_normalized: '+6284012345689',
    name: 'Dedi Susanto',
    kapso_name: 'Dedi Susanto',
    email: 'dedi.susanto@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-002',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Aerospace Engineering',
        'Aktivitas': 'working',
        'Negara Tujuan': 'UK',
        'Budget': '500jt-1m',
        'Target Berangkat': '3-6bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'Master at Imperial College London',
      },
    },
    created_at: '2026-01-14T10:15:00Z',
    updated_at: '2026-01-26T15:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-041',
    workspace_id: 'dev-workspace-001',
    phone: '+6285123456790',
    phone_normalized: '+6285123456790',
    name: 'Elisa Putri',
    kapso_name: 'Elisa Putri',
    email: 'elisa.putri@outlook.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student', 'Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Political Science',
        'Aktivitas': 'fresh_graduate',
        'Negara Tujuan': 'Netherlands',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'Master in International Politics',
      },
    },
    created_at: '2026-01-19T12:00:00Z',
    updated_at: '2026-01-23T11:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-042',
    workspace_id: 'dev-workspace-001',
    phone: '+6286234567801',
    phone_normalized: '+6286234567801',
    name: 'Fadhil Rahman',
    kapso_name: 'Fadhil Rahman',
    email: null,
    lead_score: 0,
    lead_status: 'cold',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Sports Management',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Sports coaching certificate',
      },
    },
    created_at: '2026-01-25T15:00:00Z',
    updated_at: '2026-01-25T15:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-043',
    workspace_id: 'dev-workspace-001',
    phone: '+6287345678912',
    phone_normalized: '+6287345678912',
    name: 'Gita Savitri',
    kapso_name: 'Gita Savitri',
    email: 'gita.savitri@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Parent'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Mathematics',
        'Aktivitas': 'kuliah',
        'Negara Tujuan': 'USA',
        'Budget': '>1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'native',
        'Goals': 'BSc Mathematics at MIT',
      },
    },
    created_at: '2026-01-09T08:00:00Z',
    updated_at: '2026-01-27T12:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-044',
    workspace_id: 'dev-workspace-001',
    phone: '+6288456789023',
    phone_normalized: '+6288456789023',
    name: 'Harry Gunawan',
    kapso_name: 'Harry Gunawan',
    email: 'harry.g@yahoo.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'D3',
        'Jurusan': 'Network Engineering',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Australia',
        'Budget': '100-300jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'menengah',
        'Goals': 'Bachelor in Network Security',
      },
    },
    created_at: '2026-01-17T09:00:00Z',
    updated_at: '2026-01-24T08:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-045',
    workspace_id: 'dev-workspace-001',
    phone: '+6289567890134',
    phone_normalized: '+6289567890134',
    name: 'Intan Permatasari',
    kapso_name: 'Intan Permatasari',
    email: 'intan.p@outlook.com',
    lead_score: 0,
    lead_status: 'new',
    tags: [],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'Journalism',
        'Aktivitas': 'gap_year',
        'Negara Tujuan': 'UK',
        'Budget': '100-300jt',
        'Target Berangkat': 'fleksibel',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Diploma in Media Studies',
      },
    },
    created_at: '2026-01-26T12:00:00Z',
    updated_at: '2026-01-26T12:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-046',
    workspace_id: 'dev-workspace-001',
    phone: '+6281678901245',
    phone_normalized: '+6281678901245',
    name: 'Kevin Pratama',
    kapso_name: 'Kevin Pratama',
    email: 'kevin.pratama@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-002',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Physics',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Germany',
        'Budget': '500jt-1m',
        'Target Berangkat': '3-6bulan',
        'Level Bahasa Inggris': 'skor',
        'Goals': 'PhD in Quantum Physics',
      },
    },
    created_at: '2026-01-13T11:00:00Z',
    updated_at: '2026-01-27T09:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-047',
    workspace_id: 'dev-workspace-001',
    phone: '+6282789012356',
    phone_normalized: '+6282789012356',
    name: 'Lina Anggraini',
    kapso_name: 'Lina Anggraini',
    email: null,
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student', 'Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Nutrition',
        'Aktivitas': 'fresh_graduate',
        'Negara Tujuan': 'Canada',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'Master in Dietetics',
      },
    },
    created_at: '2026-01-16T11:30:00Z',
    updated_at: '2026-01-22T14:45:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-048',
    workspace_id: 'dev-workspace-001',
    phone: '+6283890123467',
    phone_normalized: '+6283890123467',
    name: 'Mohamad Rizki',
    kapso_name: 'Mohamad Rizki',
    email: 'mohamad.rizki@yahoo.com',
    lead_score: 0,
    lead_status: 'cold',
    tags: ['Follow Up'],
    assigned_to: null,
    metadata: {
      source: 'WhatsApp',
      form_answers: {
        'Pendidikan': 'SMA',
        'Jurusan': 'E-Sports',
        'Aktivitas': 'others',
        'Negara Tujuan': 'undecided',
        'Budget': '<100jt',
        'Target Berangkat': '1-2tahun',
        'Level Bahasa Inggris': 'pemula',
        'Goals': 'Gaming industry course',
      },
    },
    created_at: '2026-01-23T16:30:00Z',
    updated_at: '2026-01-23T16:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-049',
    workspace_id: 'dev-workspace-001',
    phone: '+6284901234578',
    phone_normalized: '+6284901234578',
    name: 'Nina Marliana',
    kapso_name: 'Nina Marliana',
    email: 'nina.marliana@gmail.com',
    lead_score: 0,
    lead_status: 'hot',
    tags: ['Hot Lead', 'Student'],
    assigned_to: 'dev-user-001',
    metadata: {
      source: 'Google Form',
      form_answers: {
        'Pendidikan': 'S2',
        'Jurusan': 'Linguistics',
        'Aktivitas': 'working',
        'Negara Tujuan': 'UK',
        'Budget': '>1m',
        'Target Berangkat': '<3bulan',
        'Level Bahasa Inggris': 'native',
        'Goals': 'PhD in Applied Linguistics at Cambridge',
      },
    },
    created_at: '2026-01-08T09:00:00Z',
    updated_at: '2026-01-27T10:00:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
  {
    id: 'contact-050',
    workspace_id: 'dev-workspace-001',
    phone: '+6285012345689',
    phone_normalized: '+6285012345689',
    name: 'Oscar Wijaya',
    kapso_name: 'Oscar Wijaya',
    email: 'oscar.wijaya@outlook.com',
    lead_score: 0,
    lead_status: 'warm',
    tags: ['Student'],
    assigned_to: null,
    metadata: {
      source: 'Website',
      form_answers: {
        'Pendidikan': 'S1',
        'Jurusan': 'Agricultural Engineering',
        'Aktivitas': 'working',
        'Negara Tujuan': 'Netherlands',
        'Budget': '300-500jt',
        'Target Berangkat': '6-12bulan',
        'Level Bahasa Inggris': 'mahir',
        'Goals': 'Master in Sustainable Agriculture',
      },
    },
    created_at: '2026-01-15T13:00:00Z',
    updated_at: '2026-01-24T12:30:00Z',
    cache_updated_at: null,
    kapso_is_online: null,
    kapso_last_seen: null,
    kapso_profile_pic: null,
  },
]

export const isDevMode = () => process.env.NEXT_PUBLIC_DEV_MODE === 'true'

// Mock conversations - synced with MOCK_CONTACTS
// status: 'open' = AI active, 'handover' = Manual mode, 'closed' = Archived
export const MOCK_CONVERSATIONS_RAW: Conversation[] = [
  {
    id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-001', // Budi Santoso
    status: 'open', // AI active (ARI Active)
    assigned_to: 'dev-user-001',
    unread_count: 2,
    last_message_at: '2026-01-20T14:30:00Z',
    last_message_preview: 'Terima kasih infonya, saya akan pertimbangkan.',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-20T14:30:00Z',
  },
  {
    id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-002', // Siti Rahayu
    status: 'handover', // Manual mode (Human handling)
    assigned_to: null,
    unread_count: 1,
    last_message_at: '2026-01-22T11:00:00Z',
    last_message_preview: 'Apakah ada beasiswa untuk anak saya?',
    created_at: '2026-01-18T09:00:00Z',
    updated_at: '2026-01-22T11:00:00Z',
  },
  {
    id: 'conv-003',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-003', // Ahmad Rizky
    status: 'open', // AI active (ARI Active)
    assigned_to: 'dev-user-001',
    unread_count: 0,
    last_message_at: '2026-01-23T16:00:00Z',
    last_message_preview: 'Saya sudah siap submit aplikasi bulan depan.',
    created_at: '2026-01-20T08:00:00Z',
    updated_at: '2026-01-23T16:00:00Z',
  },
  {
    id: 'conv-004',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-004', // Dewi Lestari
    status: 'handover', // Manual mode
    assigned_to: null,
    unread_count: 3,
    last_message_at: '2026-01-21T14:00:00Z',
    last_message_preview: 'Masih bingung mau pilih negara mana...',
    created_at: '2026-01-21T14:00:00Z',
    updated_at: '2026-01-21T14:00:00Z',
  },
  {
    id: 'conv-005',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-005', // Rina Wijaya
    status: 'open', // AI active
    assigned_to: null,
    unread_count: 1,
    last_message_at: '2026-01-24T09:00:00Z',
    last_message_preview: 'Bagaimana cara apply untuk program spesialis?',
    created_at: '2026-01-22T10:00:00Z',
    updated_at: '2026-01-24T09:00:00Z',
  },
]

// Join conversations with contacts for complete data
export const MOCK_CONVERSATIONS: ConversationWithContact[] = MOCK_CONVERSATIONS_RAW.map((conv) => ({
  ...conv,
  contact: MOCK_CONTACTS.find((c) => c.id === conv.contact_id)!,
}))

// Mock messages - synced with MOCK_CONVERSATIONS
export const MOCK_MESSAGES: Message[] = [
  // Conversation with Budi Santoso
  {
    id: 'msg-001',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-001',
    content: 'Halo, saya tertarik untuk kuliah di Australia. Bisa minta info lebih lanjut?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'mock-001',
    metadata: { source: 'Website' },
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'msg-002',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'bot',
    sender_id: 'bot',
    content: 'Halo Budi! Terima kasih sudah menghubungi Eagle Overseas Education. Tentu, kami bisa bantu. Apakah sudah ada jurusan yang diminati?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'mock-002',
    metadata: {},
    created_at: '2026-01-15T10:01:00Z',
  },
  {
    id: 'msg-003',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-001',
    content: 'Saya ingin ambil jurusan IT atau Computer Science. Budget sekitar 300jt per tahun.',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'mock-003',
    metadata: {},
    created_at: '2026-01-20T14:00:00Z',
  },
  {
    id: 'msg-004',
    conversation_id: 'conv-001',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-001',
    content: 'Terima kasih infonya, saya akan pertimbangkan.',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'mock-004',
    metadata: {},
    created_at: '2026-01-20T14:30:00Z',
  },
  // Conversation with Siti Rahayu
  {
    id: 'msg-005',
    conversation_id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-002',
    content: 'Selamat siang, saya ibu dari anak yang mau kuliah ke luar negeri.',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'mock-005',
    metadata: { source: 'WhatsApp' },
    created_at: '2026-01-18T09:00:00Z',
  },
  {
    id: 'msg-006',
    conversation_id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    direction: 'outbound',
    sender_type: 'bot',
    sender_id: 'bot',
    content: 'Selamat siang, Bu! Senang bisa membantu. Anak Ibu mau kuliah di negara mana?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'mock-006',
    metadata: {},
    created_at: '2026-01-18T09:01:00Z',
  },
  {
    id: 'msg-007',
    conversation_id: 'conv-002',
    workspace_id: 'dev-workspace-001',
    direction: 'inbound',
    sender_type: 'contact',
    sender_id: 'contact-002',
    content: 'Apakah ada beasiswa untuk anak saya?',
    message_type: 'text',
    media_url: null,
    kapso_message_id: 'mock-007',
    metadata: {},
    created_at: '2026-01-22T11:00:00Z',
  },
]

// Mock notes for contacts
export interface MockNote {
  id: string
  workspace_id: string
  contact_id: string
  user_id: string
  content: string
  due_date: string | null  // Keep for UI compatibility
  is_completed: boolean  // Keep for UI compatibility
  created_at: string
}

export const MOCK_NOTES: MockNote[] = [
  {
    id: 'note-001',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-001',
    user_id: 'dev-user-001',
    content: 'Follow up about Australia visa requirements - he mentioned budget concerns',
    due_date: '2026-01-28T10:00:00Z',
    is_completed: false,
    created_at: '2026-01-20T15:00:00Z',
  },
  {
    id: 'note-002',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-001',
    user_id: 'dev-user-001',
    content: 'Sent university brochure via email',
    due_date: null,
    is_completed: true,
    created_at: '2026-01-18T11:00:00Z',
  },
  {
    id: 'note-003',
    workspace_id: 'dev-workspace-001',
    contact_id: 'contact-002',
    user_id: 'dev-user-001',
    content: 'Call back next week to discuss scholarship options for her son',
    due_date: '2026-01-30T09:00:00Z',
    is_completed: false,
    created_at: '2026-01-22T14:00:00Z',
  },
]

// Helper to get notes for a specific contact
export const getNotesForContact = (contactId: string): MockNote[] => {
  return MOCK_NOTES.filter(note => note.contact_id === contactId)
}

// Helper to get messages for a specific conversation
export const getMockMessagesForConversation = (conversationId: string): Message[] => {
  return MOCK_MESSAGES.filter(message => message.conversation_id === conversationId)
}

// Website Manager mock data
export const mockArticles: Article[] = [
  {
    id: 'article-1',
    workspace_id: 'dev-workspace-001',
    title: 'How to Choose the Right University',
    slug: 'how-to-choose-university',
    excerpt: 'A comprehensive guide to selecting the perfect university for your education abroad journey.',
    content: '# How to Choose the Right University\n\nChoosing where to study is one of the most important decisions...',
    cover_image_url: null,
    status: 'published',
    published_at: '2026-01-10T10:00:00Z',
    created_at: '2026-01-08T10:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'article-2',
    workspace_id: 'dev-workspace-001',
    title: 'Visa Application Tips for Indonesian Students',
    slug: 'visa-tips-indonesian',
    excerpt: 'Essential tips to make your student visa application process smooth and successful.',
    content: null,
    cover_image_url: null,
    status: 'draft',
    published_at: null,
    created_at: '2026-01-12T10:00:00Z',
    updated_at: '2026-01-12T10:00:00Z',
  },
]

export const mockWebinars: Webinar[] = [
  {
    id: 'webinar-1',
    workspace_id: 'dev-workspace-001',
    title: 'Study in Australia Info Session',
    slug: 'study-australia-info',
    description: 'Learn about studying in Australia, visa requirements, and scholarship opportunities.',
    cover_image_url: null,
    scheduled_at: '2026-01-25T14:00:00Z',
    duration_minutes: 60,
    meeting_url: 'https://zoom.us/j/example',
    max_registrations: 100,
    status: 'published',
    published_at: '2026-01-14T10:00:00Z',
    created_at: '2026-01-13T10:00:00Z',
    updated_at: '2026-01-14T10:00:00Z',
  },
  {
    id: 'webinar-2',
    workspace_id: 'dev-workspace-001',
    title: 'UK University Application Workshop',
    slug: 'uk-application-workshop',
    description: 'Hands-on workshop for applying to UK universities through UCAS.',
    cover_image_url: null,
    scheduled_at: '2026-02-01T15:00:00Z',
    duration_minutes: 90,
    meeting_url: null,
    max_registrations: 50,
    status: 'draft',
    published_at: null,
    created_at: '2026-01-14T10:00:00Z',
    updated_at: '2026-01-14T10:00:00Z',
  },
]

// =============================================================================
// MOCK ARI CONVERSATIONS
// Shows complete flow progression for demo mode testing
// =============================================================================

export interface MockARIMessage {
  role: 'assistant' | 'user' | 'system'
  content: string
  timestamp: number
}

export interface MockARIConversation {
  id: string
  contact_id: string
  contact_name: string
  state: 'greeting' | 'qualifying' | 'scoring' | 'routing' | 'scheduling' | 'booking'
  lead_score: number
  lead_temperature: 'cold' | 'warm' | 'hot'
  next_action: string
  messages: MockARIMessage[]
  created_at: number
  updated_at: number
}

export const MOCK_ARI_CONVERSATIONS: MockARIConversation[] = [
  {
    id: 'mock-ari-001',
    contact_id: 'contact-001',
    contact_name: 'Budi Santoso',
    state: 'qualifying',
    lead_score: 0,
    lead_temperature: 'warm',
    next_action: 'Ask about passport availability and document readiness',
    messages: [
      {
        role: 'assistant',
        content: 'Selamat siang! Saya Ari dari Eagle Overseas Education. Mau kuliah di luar negeri ya? Boleh tau namanya siapa?',
        timestamp: Date.now() - 300000, // 5 minutes ago
      },
      {
        role: 'user',
        content: 'Halo, nama saya Budi',
        timestamp: Date.now() - 280000,
      },
      {
        role: 'assistant',
        content: 'Hai kak Budi! Senang bisa bantu. Negara tujuannya kemana nih?',
        timestamp: Date.now() - 260000,
      },
      {
        role: 'user',
        content: 'Australia kak, saya tertarik jurusan IT',
        timestamp: Date.now() - 240000,
      },
      {
        role: 'assistant',
        content: 'Wah keren! IT di Australia banyak peluangnya. Oh iya kak, paspor nya udah punya belum?',
        timestamp: Date.now() - 220000,
      },
    ],
    created_at: Date.now() - 300000,
    updated_at: Date.now() - 220000,
  },
  {
    id: 'mock-ari-002',
    contact_id: 'contact-002',
    contact_name: 'Siti Rahayu',
    state: 'routing',
    lead_score: 0,
    lead_temperature: 'warm',
    next_action: 'Offer consultation slot for scholarship discussion',
    messages: [
      {
        role: 'assistant',
        content: 'Selamat siang! Saya Ari dari Eagle Overseas Education. Ada yang bisa saya bantu?',
        timestamp: Date.now() - 600000, // 10 minutes ago
      },
      {
        role: 'user',
        content: 'Selamat siang, saya ibu dari anak yang mau kuliah ke luar negeri',
        timestamp: Date.now() - 580000,
      },
      {
        role: 'assistant',
        content: 'Senang bisa membantu, Bu! Anak ibu mau kuliah di negara mana?',
        timestamp: Date.now() - 560000,
      },
      {
        role: 'user',
        content: 'Malaysia, jurusan bisnis. Ada beasiswa gak ya?',
        timestamp: Date.now() - 540000,
      },
      {
        role: 'assistant',
        content: 'Ada bu! Malaysia ada beasiswa untuk jurusan bisnis. Mau konsultasi lebih detail? Saya bisa jadwalkan dengan konsultan kami.',
        timestamp: Date.now() - 520000,
      },
    ],
    created_at: Date.now() - 600000,
    updated_at: Date.now() - 520000,
  },
]

// Helper function to get mock ARI conversation by contact ID
export const getMockAriConversation = (contactId: string): MockARIConversation | undefined => {
  return MOCK_ARI_CONVERSATIONS.find((conv) => conv.contact_id === contactId)
}

// =============================================================================
// RUNTIME MOCK WORKSPACE SETTINGS (for dev mode state management)
// =============================================================================

const MOCK_SETTINGS_STORAGE_KEY = 'my21staff-mock-workspace-settings'

// Initialize from localStorage or use defaults
function initializeMockSettings() {
  if (typeof window === 'undefined') {
    return { ...MOCK_CONVEX_WORKSPACE.settings }
  }

  try {
    const stored = localStorage.getItem(MOCK_SETTINGS_STORAGE_KEY)
    if (stored) {
      return JSON.parse(stored)
    }
  } catch (error) {
    console.error('Failed to load mock settings from localStorage:', error)
  }

  return { ...MOCK_CONVEX_WORKSPACE.settings }
}

// Mutable store for workspace settings in dev mode
// This allows Settings page updates to reflect in Database page
let runtimeMockSettings = initializeMockSettings()

export const getMockWorkspaceSettings = () => {
  return runtimeMockSettings
}

export const updateMockWorkspaceSettings = (updates: Partial<typeof runtimeMockSettings>) => {
  runtimeMockSettings = { ...runtimeMockSettings, ...updates }

  // Persist to localStorage
  if (typeof window !== 'undefined') {
    try {
      localStorage.setItem(MOCK_SETTINGS_STORAGE_KEY, JSON.stringify(runtimeMockSettings))
    } catch (error) {
      console.error('Failed to save mock settings to localStorage:', error)
    }

    // Dispatch event to notify components of settings change
    window.dispatchEvent(new CustomEvent('mockWorkspaceSettingsUpdated', { detail: runtimeMockSettings }))
  }
}

export const resetMockWorkspaceSettings = () => {
  runtimeMockSettings = { ...MOCK_CONVEX_WORKSPACE.settings }

  // Clear from localStorage
  if (typeof window !== 'undefined') {
    try {
      localStorage.removeItem(MOCK_SETTINGS_STORAGE_KEY)
    } catch (error) {
      console.error('Failed to clear mock settings from localStorage:', error)
    }
  }
}
