// Generated by Convex
// This is a stub for Vercel builds when Convex types can't be generated
// Update this file after running: npx convex codegen

import type { FunctionReference } from "convex/server";

// Workspaces
export type Workspaces = {
  _id: string;
  name: string;
  slug: string;
  owner_id: string;
  kapso_phone_id?: string;
  meta_access_token?: string;
  settings?: any;
  created_at: number;
  updated_at: number;
};

// Workspace Members
export type WorkspaceMembers = {
  _id: string;
  workspace_id: string;
  user_id: string;
  role: string;
  settings?: any;
  created_at: number;
};

// Contacts
export type Contacts = {
  _id: string;
  workspace_id: string;
  phone: string;
  phone_normalized?: string;
  name?: string;
  kapso_name?: string;
  email?: string;
  lead_score: number;
  lead_status: string;
  tags?: string[];
  assigned_to?: string;
  source?: string;
  metadata?: any;
  cache_updated_at?: number;
  created_at: number;
  updated_at: number;
  supabaseId: string;
};

// Conversations
export type Conversations = {
  _id: string;
  workspace_id: string;
  contact_id: string;
  status: string;
  assigned_to?: string;
  unread_count: number;
  last_message_at?: number;
  last_message_preview?: string;
  created_at: number;
  updated_at: number;
  supabaseId: string;
};

// Messages
export type Messages = {
  _id: string;
  conversation_id: string;
  workspace_id: string;
  direction: string;
  sender_type: string;
  sender_id?: string;
  content?: string;
  message_type: string;
  media_url?: string;
  kapso_message_id?: string;
  metadata?: any;
  created_at: number;
  supabaseId: string;
};

// Contact Notes
export type ContactNotes = {
  _id: string;
  workspace_id: string;
  contact_id: string;
  created_by: string;
  content: string;
  due_date?: number;
  completed: boolean;
  created_at: number;
  updated_at: number;
  supabaseId: string;
};

// Tickets
export type Tickets = {
  _id: string;
  workspace_id: string;
  client_workspace_id?: string;
  reporter_user_id?: string;
  category: string;
  priority: string;
  stage: string;
  title: string;
  description: string;
  steps?: Record<string, any>;
  reopen_token?: string;
  attachments?: string[];
  assigned_to?: string;
  status: "open" | "in_progress" | "waiting" | "resolved" | "closed";
  created_at: number;
  updated_at: number;
  supabaseId: string;
};

// Workspaces functions
export type WorkspacesQuery =
  | "by_id"
  | "by_slug"
  | "by_kapso_phone_id";

export type WorkspacesMutation =
  | "create"
  | "update"
  | "updateSettings"
  | "delete";

// WorkspaceMembers functions
export type WorkspaceMembersQuery =
  | "listByWorkspace"
  | "getByUserWorkspace"
  | "checkMembership";

export type WorkspaceMembersMutation =
  | "create"
  | "update"
  | "delete"
  | "updateSettings";

// Contacts functions
export type ContactsQuery =
  | "listWithFilters"
  | "getByPhone"
  | "getByPhoneNormalized"
  | "getByWorkspace"
  | "getByLeadStatus"
  | "getByTags"
  | "search";

export type ContactsMutation =
  | "create"
  | "update"
  | "updateLeadScore"
  | "updateLeadStatus"
  | "delete"
  | "upsert"
  | "batchUpsert";

// Conversations functions
export type ConversationsQuery =
  | "listWithFilters"
  | "getById"
  | "getByContact"
  | "getActiveForContact"
  | "getUnreadCount";

export type ConversationsMutation =
  | "create"
  | "update"
  | "markRead"
  | "close"
  | "assign"
  | "handover"
  | "updateUnreadCount";

// Messages functions
export type MessagesQuery =
  | "listByConversation"
  | "getByKapsoId"
  | "getLastByConversation"
  | "getCountByConversation";

export type MessagesMutation =
  | "create"
  | "batchCreate"
  | "updateReplyContext"
  | "updateMediaUrl";

// ContactNotes functions
export type ContactNotesQuery =
  | "listByContact"
  | "listByWorkspace"
  | "getById";

export type ContactNotesMutation =
  | "create"
  | "update"
  | "complete"
  | "delete";

// Tickets functions
export type TicketsQuery =
  | "list"
  | "getById"
  | "listByWorkspace"
  | "listByClient"
  | "getByStage"
  | "getByCategory"
  | "search";

export type TicketsMutation =
  | "create"
  | "update"
  | "transition"
  | "reopen"
  | "assign"
  | "delete"
  | "addStep";

// API type exports
export type API = {
  workspaces: {
    [K in WorkspacesQuery]: FunctionReference<"query", K>;
  } & {
    [K in WorkspacesMutation]: FunctionReference<"mutation", K>;
  };
  workspaceMembers: {
    [K in WorkspaceMembersQuery]: FunctionReference<"query", K>;
  } & {
    [K in WorkspaceMembersMutation]: FunctionReference<"mutation", K>;
  };
  contacts: {
    [K in ContactsQuery]: FunctionReference<"query", K>;
  } & {
    [K in ContactsMutation]: FunctionReference<"mutation", K>;
  };
  conversations: {
    [K in ConversationsQuery]: FunctionReference<"query", K>;
  } & {
    [K in ConversationsMutation]: FunctionReference<"mutation", K>;
  };
  messages: {
    [K in MessagesQuery]: FunctionReference<"query", K>;
  } & {
    [K in MessagesMutation]: FunctionReference<"mutation", K>;
  };
  contactNotes: {
    [K in ContactNotesQuery]: FunctionReference<"query", K>;
  } & {
    [K in ContactNotesMutation]: FunctionReference<"mutation", K>;
  };
  tickets: {
    [K in TicketsQuery]: FunctionReference<"query", K>;
  } & {
    [K in TicketsMutation]: FunctionReference<"mutation", K>;
  };
  // Webhook HTTP action
  webhook: {
    kapso: FunctionReference<"action", "webhook/kapso">;
  };
};

// Default export for compatibility
export default function api(): API;
export const api: API;
