// Generated by Convex
// This is a stub for Vercel builds when Convex types can't be generated

export type QueryCtx = any;
export type MutationCtx = any;
export type ActionCtx = any;

export type Doc<T> = T & {
  _id: string;
  _creationTime: number;
};

export type TableNames = any;

export const v = {
  string: () => string,
  number: () => number,
  boolean: () => boolean,
  null: () => null,
  optional: <T>(v: T) => T | null | undefined,
  array: <T>(v: T) => T[],
  any: () => any,
  literal: <T extends string>(t: T) => T,
  object: <T extends Record<string, any>>(obj: T) => T,
  record: <K extends string, V>(keys: K[], values: V[]) => Record<K, V>,
  id: () => string,
};

export function defineSchema(schema: any): any;
export function defineTable<T>(table: T): any;
