// @ts-nocheck
// @generated
import type { DataModel } from "./dataModel.js";
/**
 * Generated by Convex
 */
export default function makePublicApi(api) {
  api.tickets = {
    createTicket: {
      args: {
        workspace_id: { type: "string" },
        requester_id: { type: "string" },
        title: { type: "string" },
        description: { type: "string" },
        category: { type: "string" },
        priority: { type: "string" },
        admin_workspace_id: { type: "string", optional: true },
      },
      returns: {
        found: { type: "boolean" },
      },
    },
    updateTicket: {
      args: {
        ticket_id: { type: "string" },
        workspace_id: { type: "string" },
        assigned_to: { type: "string", optional: true },
      },
      returns: {
        found: { type: "boolean" },
      },
    },
    approveTicketStageSkip: {
      args: {
        ticket_id: { type: "string" },
        workspace_id: { type: "string" },
        approved: { type: "boolean" },
        user_id: { type: "string" },
      },
      returns: {
        found: { type: "boolean" },
      },
    },
    reopenTicket: {
      args: {
        ticket_id: { type: "string" },
        workspace_id: { type: "string" },
        user_id: { type: "string", optional: true },
      },
      returns: {
        found: { type: "boolean" },
      },
    },
    transitionTicketStage: {
      args: {
        ticket_id: { type: "string" },
        workspace_id: { type: "string" },
        to_stage: { type: "string" },
        user_id: { type: "string" },
        is_skip: { type: "boolean", optional: true },
      },
      returns: {
        found: { type: "boolean" },
      },
    },
  };
}
